package com.space.entity;

public class SQLConstant {
	public static String ZYNF="";
	public static String INTF="";
	/* 总帐余额表 */
//	public static String balanceSql="SELECT WMSYS.WM_CONCAT(FV.CHECKTYPE) CHECKTYPE, WMSYS.WM_CONCAT(FV.VALUECODE) VALUECODE," +
//			"WMSYS.WM_CONCAT(FV.VALUENAME) VALUENAME,WMSYS.WM_CONCAT(FV.CHECKVALUE) CHECKVALUE,BA.PK_ACCSUBJ,BA.PK_BALANCE,BA.DR,FV.FREEVALUEID," +
//			"' ' SENCE,BA.YEAR||'-'||BA.PERIOD period,SU.SUBJCODE,SU.BALANORIENT,SU.SUBJNAME,BA.PK_CURRTYPE,BA.PK_CORP,BA.DEBITAMOUNT,BA.CREDITAMOUNT," +
//			"BA.LOCALDEBITAMOUNT,BA.LOCALCREDITAMOUNT,BA.TS,BD.UNITCODE,BD.UNITNAME FROM GL_BALANCE BA  " +
//			"LEFT JOIN GL_FREEVALUE FV ON BA.ASSID=FV.FREEVALUEID " +
//			"LEFT JOIN BD_ACCSUBJ SU ON BA.PK_ACCSUBJ=SU.PK_ACCSUBJ " +
//			"LEFT JOIN BD_CORP BD ON BA.PK_CORP=BD.PK_CORP  WHERE BA.YEAR>='2011' " +
//			"GROUP BY BA.PK_ACCSUBJ,BA.PK_BALANCE,BA.DR,FV.FREEVALUEID,BA.YEAR," +
//			"BA.PK_CURRTYPE,BA.PK_CORP,BA.DEBITAMOUNT,BA.CREDITAMOUNT," +
//			"BA.LOCALDEBITAMOUNT,BA.LOCALCREDITAMOUNT,BA.TS,SU.SUBJCODE,SU.SUBJNAME,BA.PERIOD,BD.UNITCODE,BD.UNITNAME,SU.BALANORIENT ";
	
	public static String balanceSql="SELECT WMSYS.WM_CONCAT(A.NU||'|'||A.CHECKTYPE) CHECKTYPE, WMSYS.WM_CONCAT(A.NU||'|'||A.VALUECODE) VALUECODE,WMSYS.WM_CONCAT(A.NU||'|'||A.VALUENAME) VALUENAME," +
			"WMSYS.WM_CONCAT(A.NU||'|'||A.CHECKVALUE) CHECKVALUE,A.PK_ACCSUBJ,A.PK_BALANCE,A.DR,A.FREEVALUEID,A.YEAR," +
			"A.SENCE,A.PK_CURRTYPE,A.PK_CORP,A.DEBITAMOUNT,A.CREDITAMOUNT,A.LOCALDEBITAMOUNT,A.LOCALCREDITAMOUNT,A.TS,A.SUBJCODE,A.SUBJNAME,A.PERIOD,A.UNITCODE,A.UNITNAME,A.BALANORIENT " +
			"FROM (SELECT rownum NU,FV.CHECKTYPE,FV.CHECKVALUE,FV.VALUECODE,FV.VALUENAME,BA.PK_ACCSUBJ,BA.PK_BALANCE,BA.DR,FV.FREEVALUEID," +
			"' ' SENCE,BA.YEAR||'-'||BA.PERIOD period,SU.SUBJCODE,SU.BALANORIENT,SU.SUBJNAME,BA.PK_CURRTYPE,BA.PK_CORP,BA.DEBITAMOUNT,BA.CREDITAMOUNT," +
			"BA.LOCALDEBITAMOUNT,BA.LOCALCREDITAMOUNT,BA.TS,BD.UNITCODE,BD.UNITNAME,BA.YEAR FROM "+ZYNF+"GL_BALANCE BA  " +
			"LEFT JOIN "+ZYNF+"GL_FREEVALUE FV ON BA.ASSID=FV.FREEVALUEID " +
			"LEFT JOIN "+ZYNF+"BD_ACCSUBJ SU ON BA.PK_ACCSUBJ=SU.PK_ACCSUBJ " +
			"LEFT JOIN "+ZYNF+"BD_CORP BD ON BA.PK_CORP=BD.PK_CORP  WHERE BA.YEAR>='2011' ) A GROUP BY A.PK_ACCSUBJ,A.PK_BALANCE,A.DR,A.FREEVALUEID,A.YEAR," +
			"A.PK_CURRTYPE,A.PK_CORP,A.DEBITAMOUNT,A.CREDITAMOUNT,A.LOCALDEBITAMOUNT,A.LOCALCREDITAMOUNT,A.TS," +
			"A.SUBJCODE,A.SUBJNAME,A.SENCE,A.PERIOD,A.UNITCODE,A.UNITNAME,A.BALANORIENT ";
	//CASE WHEN P3!=NULL THEN 3 WHEN P3==NULL&&P2!=NULL 2 WHEN P2==NULL&&P1!=NULL THEN 1 WHEN P1==NULL THEN 0 END FLAG,
	
	
	/* 凭证头表*/
	public static String vouHeadSql= "SELECT CASE WHEN VH.PK_MANAGER IS NOT NULL THEN '已记账' WHEN VH.PK_MANAGER IS NULL AND " +
			"VH.PK_CHECKED IS NOT NULL THEN '审核' WHEN VH.PK_CHECKED IS NULL AND VH.PK_PREPARED IS NOT NULL THEN '已制单' END FLAG," +
			"US.USER_CODE,US.USER_NAME,VH.NO,VH.DR,'GL' PK_SYSTEM,VH.PK_VOUCHER,VH.PREPAREDDATE," +
			"VH.PK_PREPARED,VH.PK_SOURCEPK,VH.TS,VH.PK_CORP,BD.UNITCODE,BD.UNITNAME FROM "+ZYNF+"GL_VOUCHER VH " +
			"LEFT JOIN "+ZYNF+"SM_USER US ON VH.PK_PREPARED=US.CUSERID " +
			"LEFT JOIN "+ZYNF+"BD_CORP BD ON VH.PK_CORP=BD.PK_CORP WHERE VH.YEAR>='2011' ";
	/* 凭证明细表*/
//	public static String vouDetailSql="SELECT WMSYS.WM_CONCAT(FV.CHECKTYPE) CHECKTYPE, WMSYS.WM_CONCAT(FV.VALUECODE) VALUECODE," +
//			"WMSYS.WM_CONCAT(FV.VALUENAME) VALUENAME,WMSYS.WM_CONCAT(FV.CHECKVALUE) CHECKVALUE, VD.DETAILINDEX," +
//			"VD.YEARV,SU.BALANORIENT,SU.PK_ACCSUBJ,SU.SUBJCODE,SU.SUBJNAME,VD.PK_DETAIL,VD.DR,VD.PK_VOUCHER,VD.PK_CURRTYPE,VD.PK_CORP," +
//			"VD.DEBITAMOUNT,VD.CREDITAMOUNT,VD.LOCALDEBITAMOUNT,VD.LOCALCREDITAMOUNT,VD.TS,BD.UNITCODE,BD.UNITNAME " +
//			"FROM GL_DETAIL VD " +
//			"LEFT JOIN BD_ACCSUBJ SU ON VD.PK_ACCSUBJ=SU.PK_ACCSUBJ " +
//			"LEFT JOIN GL_FREEVALUE FV ON VD.ASSID=FV.FREEVALUEID " +
//			"LEFT JOIN BD_CORP BD ON VD.PK_CORP=BD.PK_CORP WHERE YEARV>='2011' and pk_voucher='1002V710000000065G38'" +
//			"GROUP BY VD.DETAILINDEX,VD.YEARV,SU.BALANORIENT,SU.PK_ACCSUBJ,SU.SUBJCODE,SU.SUBJNAME," +
//			"VD.PK_DETAIL,VD.DR,VD.PK_VOUCHER,VD.PK_CURRTYPE,VD.PK_CORP,VD.DEBITAMOUNT,VD.CREDITAMOUNT," +
//			"VD.LOCALDEBITAMOUNT,VD.LOCALCREDITAMOUNT,VD.TS, BD.UNITCODE,BD.UNITNAME ";
	
	
	
	public static String vouDetailSql="SELECT WMSYS.WM_CONCAT(A.NU||'|'||A.CHECKTYPE) CHECKTYPE, WMSYS.WM_CONCAT(A.NU||'|'||A.VALUECODE) VALUECODE,WMSYS.WM_CONCAT(A.NU||'|'||A.VALUENAME) VALUENAME," +
			"WMSYS.WM_CONCAT(A.NU||'|'||A.CHECKVALUE) CHECKVALUE,A.DETAILINDEX,A.YEARV,A.BALANORIENT,A.PK_ACCSUBJ,A.SUBJCODE," +
			"A.SUBJNAME,A.PK_DETAIL,A.DR,A.PK_VOUCHER,A.PK_CURRTYPE,A.PK_CORP,A.DEBITAMOUNT,A.CREDITAMOUNT,A.LOCALDEBITAMOUNT," +
			"A.LOCALCREDITAMOUNT,A.TS, A.UNITCODE,A.UNITNAME  FROM " +
			"(SELECT ROWNUM NU, VD.DETAILINDEX,FV.CHECKTYPE,FV.CHECKVALUE,FV.VALUECODE,FV.VALUENAME,VD.YEARV,SU.BALANORIENT," +
			"SU.PK_ACCSUBJ,SU.SUBJCODE,SU.SUBJNAME,VD.PK_DETAIL,VD.DR,VD.PK_VOUCHER,VD.PK_CURRTYPE,VD.PK_CORP,VD.DEBITAMOUNT," +
			"VD.CREDITAMOUNT,VD.LOCALDEBITAMOUNT,VD.LOCALCREDITAMOUNT,VD.TS,BD.UNITCODE,BD.UNITNAME FROM "+ZYNF+"GL_DETAIL VD " +
			"LEFT JOIN "+ZYNF+"BD_ACCSUBJ SU ON VD.PK_ACCSUBJ=SU.PK_ACCSUBJ LEFT JOIN "+ZYNF+"GL_FREEVALUE FV ON VD.ASSID=FV.FREEVALUEID " +
			"LEFT JOIN "+ZYNF+"BD_CORP BD ON VD.PK_CORP=BD.PK_CORP WHERE YEARV>='2011' ) A " +// or pk_voucher='1002V810000000000HQV' or pk_voucher='1002V21000000005WM5S'
			"GROUP BY A.DETAILINDEX," +
			"A.YEARV,A.BALANORIENT,A.PK_ACCSUBJ,A.SUBJCODE,A.SUBJNAME,A.PK_DETAIL,A.DR,A.PK_VOUCHER,A.PK_CURRTYPE,A.PK_CORP," +
			"A.DEBITAMOUNT,A.CREDITAMOUNT,A.LOCALDEBITAMOUNT,A.LOCALCREDITAMOUNT,A.TS, A.UNITCODE,A.UNITNAME ";
	
	
	
	
	
	
	
	
	
	
	
	
	// WHERE PK_DETAIL='1002V81000000001C4T6
	/* 公司代码 */
	public static String vCorpSql="SELECT BC.PK_CORP PK_SUBJCODE,BC.UNITCODE AS SUBJCODE,BC.UNITNAME AS SUBJNAME,BC.BEGINDATE,BC.CREATEDATE," 
		+"BC.ENDDATE,BC.TS AS UPDATEDATE,'' PROPERTY,'WISDRI_COA_COM' VALUE,PK_CORP COMCODE FROM "+ZYNF+"BD_CORP BC ";
	/* 成本中心段*/
	public static String vDeptSql="SELECT DE.PK_DEPTDOC PK_SUBJCODE,DE.PK_CORP,DE.PK_FATHEDEPT,DE.DEPTCODE SUBJCODE,DE.DEPTNAME SUBJNAME," +
			"'' BEGINDATE,DE.CREATEDATE,'' ENDDATE,DE.TS AS UPDATEDATE,'' PROPERTY,'WISDRI_COA_CC' VALUE,PK_CORP COMCODE FROM "+ZYNF+"BD_DEPTDOC DE";
	/* 客商段*/
	public static String vCustSql="SELECT distinct '' CREATEDATE,CM.PK_CUBASDOC PK_SUBJCODE,CM.PK_CORP ,CB.CUSTCODE SUBJCODE,CB.CUSTNAME SUBJNAME," +
			"'' BEGINDATE,'' ENDDATE,CB.TS AS UPDATEDATE ,'' PROPERTY,'WISDRI_COA_PARTY' VALUE,CM.PK_CORP COMCODE FROM "+ZYNF+"BD_CUBASDOC CB " +
			"LEFT JOIN "+ZYNF+"BD_CUMANDOC CM ON CB.PK_CUBASDOC=CM.PK_CUBASDOC";
	/*项目段*/
	public static String vProjectSql="SELECT '' CREATEDATE,BM.PK_JOBMNGFIL PK_SUBJCODE,BF.PK_CORP ,BF.JOBCODE SUBJCODE," +
			"BF.JOBNAME SUBJNAME,BF.BEGINDATE,BF.ENDDATE,BF.TS AS UPDATEDATE ," +
			"'' PROPERTY,CASE WHEN PK_JOBTYPE IN(SELECT PK_JOBTYPE FROM "+ZYNF+"BD_JOBTYPE WHERE JOBTYPENAME LIKE '%合同%') " +
			"THEN 'WISDRI_COA_SP2' ELSE 'WISDRI_COA_PRO' END VALUE,BM.PK_CORP COMCODE FROM "+ZYNF+"BD_JOBBASFIL BF " +
			"LEFT JOIN "+ZYNF+"BD_JOBMNGFIL BM ON BF.PK_JOBBASFIL=BM.PK_JOBBASFIL";
	/* 科目段*/
	public static String vSubjSql="SELECT '' CREATEDATE," +
			"SUJ.PK_ACCSUBJ PK_SUBJCODE,SUJ.PK_CORP ,SUJ.SUBJCODE,SUJ.SUBJNAME," +
			"'' BEGINDATE,SUJ.ENDYEAR ENDDATE,SUJ.TS UPDATEDATE," +
			"'' PROPERTY,'WISDRI_COA_ACC' VALUE,PK_CORP COMCODE FROM "+ZYNF+"BD_ACCSUBJ SUJ";
	/*明细*/
	public static String vMXsql="SELECT '' CREATEDATE,CI.PK_ACCID PK_SUBJCODE,CI.PK_CORP COMCODE,CI.ACCIDCODE SUBJCODE,CI.ACCIDNAME SUBJNAME,'' BEGINDATE,'' ENDDATE,CI.TS AS UPDATEDATE " +
			",'' PROPERTY,'WISDRI_COA_SUBACC' VALUE FROM "+ZYNF+"BD_ACCID CI WHERE CI.PK_CORP!='0001' " +
			"UNION " +
			"SELECT  '' CREATEDATE,CL.PK_PSNCL PK_SUBJCODE,CL.PK_CORP COMCODE,CL.PSNCLASSCODE SUBJCODE,CL.PSNCLASSNAME SUBJNAME,'' BEGINDATE,'' ENDDATE,CL.TS AS UPDATEDATE " +
			",'' PROPERTY,'WISDRI_COA_SUBACC' VALUE FROM "+ZYNF+"BD_PSNCL CL " +
			"UNION " +
			"SELECT  '' CREATEDATE,BO.PK_DEFDOC PK_SUBJCODE,BO.PK_CORP COMCODE,BO.DOCCODE SUBJCODE,BO.DOCNAME SUBJNAME,'' BEGINDATE,'' ENDDATE,BO.TS AS UPDATEDATE " +
			",'' PROPERTY,'WISDRI_COA_SUBACC' VALUE FROM "+ZYNF+"BD_DEFDOC BO WHERE BO.PK_DEFDOCLIST='0001V21000000000OUP3' OR BO.PK_DEFDOCLIST='0001V41000000000P85S'";
	
	
	//层级表
	/*公司层级*/
	public static String cCorpSql="SELECT CO.UNITNAME MNAME,CO.PK_CORP PKNC,'WISDRI_COA_COM' VALUE,'' COMCODE,'' CREATOR,'' UPDATOR,CO.CREATEDATE," +
			"CO.TS UPDATEDATE,CO.UNITCODE UCODE,CO.FATHERCORP FATHER FROM "+ZYNF+"BD_CORP CO";
	/* 部门层级*/
	public static String cDeptSql="SELECT DO.PK_DEPTDOC PKNC,'WISDRI_COA_CC' VALUE,DO.PK_CORP COMCODE,'' CREATOR," +
			"'' UPDATOR,DO.CREATEDATE,DO.TS UPDATEDATE,DO.DEPTNAME MNAME,DO.PK_DEPTDOC UCODE,DO.PK_FATHEDEPT " +
			"FATHER FROM "+ZYNF+"BD_DEPTDOC DO";
	/* 客商层级，无层级关系密*/
	public static String cCustSql="SELECT CU.PK_CUBASDOC PKNC,'WISDRI_COA_PARTY' VALUE,CU.PK_CORP COMCODE,'' CREATOR,'' UPDATOR,'' CREATEDATE," +
			"CU.TS UPDATEDATE,CU.CUSTNAME MNAME,CU.CUSTCODE UCODE,'' FATHER FROM "+ZYNF+"BD_CUBASDOC CU";
	/*项目层级*/
	public static String cProjectSql="SELECT JB.PK_JOBBASFIL PKNC,CASE WHEN PK_JOBTYPE IN" +
			"(SELECT PK_JOBTYPE FROM "+ZYNF+"BD_JOBTYPE WHERE JOBTYPENAME LIKE '%合同%') " +
			"THEN 'WISDRI_COA_SP2' ELSE 'WISDRI_COA_PRO' END VALUE," +
			"JB.PK_CORP COMCODE,'' CREATOR,'' UPDATOR,'' CREATEDATE,JB.TS UPDATEDATE," +
			"JB.JOBNAME MNAME,JB.JOBCODE UCODE,'' FATHER " +
			"FROM "+ZYNF+"BD_JOBBASFIL JB";
	/*科目层级*/
	public static String cSubjSql="SELECT AC.PK_ACCSUBJ PKNC,'WISDRI_COA_ACC' VALUE,AC.PK_CORP COMCODE," +
			"'' CREATOR,'' UPDATOR,'' CREATEDATE,AC.TS UPDATEDATE,AC.SUBJNAME MNAME,AC.SUBJCODE UCODE," +
			"DECODE(SUBJLEV,'1','','2',SUBSTR(SUBJCODE,1,4),'3',SUBSTR(SUBJCODE,1,6),'4'," +
			"SUBSTR(SUBJCODE,1,8),'5',SUBSTR(SUBJCODE,1,10)) FATHER FROM "+ZYNF+"BD_ACCSUBJ AC";
	/*明细层级*/
	public static String cMxSql="SELECT CI.PK_ACCID PKNC,'WISDRI_COA_SUBACC' VALUE,'' COMCODE,'' CREATOR,'' UPDATOR," +
			"'' CREATEDATE,CI.TS UPDATEDATE,CI.ACCIDNAME MNAME,CI.ACCIDCODE UCODE,'' FATHER FROM "+ZYNF+"BD_ACCID CI WHERE CI.PK_CORP!='0001'" +
			" UNION " +
			"SELECT   CL.PK_PSNCL PKNC,'WISDRI_COA_SUBACC' VALUE,'' COMCODE,'' CREATOR,'' UPDATOR," +
			"'' CREATEDATE,CL.TS UPDATEDATE,CL.PSNCLASSNAME MNAME,CL.PSNCLASSCODE UCODE,'' FATHER FROM "+ZYNF+"BD_PSNCL CL " +
			"UNION " +
			"SELECT  BO.PK_DEFDOC PKNC,'WISDRI_COA_SUBACC' VALUE,'' COMCODE,'' CREATOR,'' UPDATOR," +
			"'' CREATEDATE,BO.TS UPDATEDATE,BO.DOCNAME MNAME,BO.DOCCODE UCODE,'' FATHER FROM "+ZYNF+"BD_DEFDOC BO " +
			"WHERE BO.PK_DEFDOCLIST='0001V21000000000OUP3' OR BO.PK_DEFDOCLIST='0001V41000000000P85S'";
}
